pipeline:
  backend:
    image: docker
    privileged: true
    commands:
      - docker build -t tmp .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  docker:
    image: plugins/docker
