pipeline:
  backend:
    image: docker
    privileged: true
    commands:
      - echo $DOCKER_PASSWORD
      - echo ${DOCKER_PASSWORD}
      - echo $${DOCKER_PASSWORD}
      - docker login -u krotkiewicz -p ${DOCKER_PASSWORD}
      - docker build -t ulamlabs/drone-test .
      - docker push ulamlabs/drone-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_password ]
